const dummyText = [
  'cute cats',
  'cartoon characters',
  'mansions',
  'beautiful bridges',
  'abstract concepts',
  'super computers',
  'young boys',
  'old women',
  'african culture',
  'dairy products',
  'wonderful books',
  'volcanic eruptions',
  'rock formation',
  'hackers at work',
  'weeds',
  'game of thrones',
  'white walkers',
  'cheese',
  'fries',
  'popcorns',
  'chocolate',
  'ice cream',
  'laptops',
  'cup of coffee',
  'bread',
  'soccer',
  'football',
  'basketball',
  'curtains',
  'window designs',
  'african wear',
  'concentration of air',
  'dust particles',
  'diffusion',
  'osmosis',
  'cars',
  'f1 racing cars',
  'cars in mud',
  'leaves',
  'fences',
  'colourful notebooks',
  'futuristic technology design',
]

const testRequest = dummyText[Math.floor(Math.random() * dummyText.length)]

export { testRequest }